import {test,expect} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

const backend=process.env.HALCON_TEST_BACKEND||'http://127.0.0.1:3301'
test('React: login, responsive, accessibility, sharing, GPS and logout',async({page,context})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await context.grantPermissions(['geolocation']);await context.setGeolocation({latitude:23.1136,longitude:-82.3666})
  await page.goto('/')
  await page.getByLabel('Correo electrónico').fill('browser0@example.test');await page.getByLabel('Contraseña',{exact:true}).fill('BrowserTest123!')
  await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Comparte tu recorrido'})).toBeVisible()
  await expect(page.getByText('Conectado',{exact:true})).toBeVisible()
  for(const width of [320,390,768,1440]) {
    await page.setViewportSize({width,height:900})
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
    await expect(page.getByLabel('¿Con quién quieres compartir?')).toBeVisible()
    const box=await page.getByRole('button',{name:'Activar ubicación'}).boundingBox();expect(box!.height).toBeGreaterThanOrEqual(44)
  }
  const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()
  expect(audit.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([])
  await page.getByLabel('¿Con quién quieres compartir?').fill('nobody@example.test');await page.getByRole('button',{name:'Guardar',exact:true}).click()
  await expect(page.getByText('Indica el correo de una cuenta activa distinta a la tuya.')).toBeVisible()
  await expect(page.getByLabel('¿Con quién quieres compartir?')).toHaveValue('nobody@example.test')
  await page.getByLabel('¿Con quién quieres compartir?').fill('browser1@example.test');await page.getByRole('button',{name:'Guardar',exact:true}).click()
  await expect(page.getByText(/Compartiendo con Bruno/)).toBeVisible()
  expect(await page.evaluate(()=>(window as any).__xss)).toBeUndefined()
  await page.getByRole('button',{name:'Activar ubicación'}).click();await expect(page.getByText('Transmitiendo. Mantén esta página abierta.')).toBeVisible()
  await expect(page.getByText(/23\.11360, -82\.36660/)).toBeVisible()
  await page.getByRole('button',{name:'Detener transmisión'}).click();await expect(page.getByRole('button',{name:'Activar ubicación'})).toBeEnabled()
  await page.getByRole('button',{name:'Retirar acceso'}).click();await expect(page.getByText('Acceso retirado.',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Cerrar sesión'}).click();await expect(page.getByRole('heading',{name:'Inicia sesión',exact:true})).toBeVisible()
  expect(errors).toEqual([])
  await page.screenshot({path:'test-results/react-mobile.png',fullPage:true})
})

test('Goravel views: responsive, keyboard, no-reload forms and reduced motion',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto(`${backend}/login`)
  await page.locator('[name="email"]').fill('browser0@example.test');await page.locator('[name="password"]').fill('BrowserTest123!')
  await page.locator('form[action="/login"] button[type="submit"]').click();await page.waitForURL('**/profile')
  await expect(page.getByRole('heading',{name:'Comparte tu recorrido'})).toBeVisible()
  for(const width of [320,390,768,1440]) {
    await page.setViewportSize({width,height:900})
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
    const input=await page.locator('#recipient-email').boundingBox();expect(input!.width).toBeLessThanOrEqual(width)
  }
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.locator('#recipient-email').fill('browser1@example.test');await page.locator('#recipient-save').click()
  await expect(page.locator('#recipient-current')).toContainText('Bruno')
  await expect(page.locator('#recipient-feedback')).toContainText('Destinatario guardado')
  expect(page.url()).toBe(`${backend}/profile`)
  expect(await page.evaluate(()=>(window as any).__xss)).toBeUndefined()
  await page.locator('#recipient-remove').click();await expect(page.locator('#recipient-feedback')).toContainText('Acceso retirado')
  await page.locator('#recipient-email').focus();await page.keyboard.press('Tab');await expect(page.locator('#recipient-save')).toBeFocused()
  const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()
  expect(audit.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))).toEqual([])
  await page.screenshot({path:'test-results/goravel-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/goravel-mobile.png',fullPage:true})
  expect(errors).toEqual([])
})

test('Moderator: create, assign, see own halcones and delete with a native form',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto(`${backend}/login`)
  await page.locator('[name="email"]').fill('browser2@example.test')
  await page.locator('[name="password"]').fill('BrowserTest123!')
  await page.locator('form[action="/login"] button[type="submit"]').click()
  await page.waitForURL('**/profile')
  await expect(page.locator('.tf-map-live__item-name').filter({hasText:'Dispositivo del moderador'})).toBeVisible()
  await page.goto(`${backend}/moderator/halcones`)
  await page.locator('[data-open-dialog="dlg-create-halcon"]').first().click()
  await page.locator('#new-halcon-name').fill('Dispositivo de prueba E2E')
  await page.locator('#dlg-create-halcon button[type="submit"]').click()
  await expect(page).toHaveURL(/ok=creado/)
  const row=page.locator('tbody tr').filter({hasText:'Dispositivo de prueba E2E'})
  await expect(row).toBeVisible()
  const dialogID=await row.locator('[data-open-dialog]').getAttribute('data-open-dialog')
  await row.locator('[data-open-dialog]').click()
  await page.locator(`#${dialogID} select[name="user_id"]`).selectOption('1')
  await page.locator(`#${dialogID} button[type="submit"]`).click()
  await expect(page).toHaveURL(/ok=asignado/)
  await expect(row).toContainText('Alicia de prueba')
  page.once('dialog',dialog=>dialog.accept())
  await row.locator('button[title="Eliminar"]').click()
  await expect(page).toHaveURL(/ok=eliminado/)
  await expect(row).toHaveCount(0)
  expect(errors).toEqual([])
})
